### ISSUE TITLE
Basic install documentation

### ISSUE THREAD

**Issue by pohutukawa** [josteink/structurizr-ts-mode#1]
Would it be possible to provide some basic instructions on how to install the different prerequisites and how to install the extension into Emacs?

Thanks in advance.

**Comment by josteink** [comment]
That's a fair point. I've tried to amend the README to make this more obvious.

Check it out, and let me know if it works for you?

**Comment by josteink** [comment]
Hey there and thanks for the extensive bug report!

The part about 

````lisp
(add-to-list 'treesit-language-source-alist
             '(structurizr . ("/Users/josteink/build/tree-sitter-structurizr" "master")))
````

is clearly a mistake on my part, which is meant to aid `treesit-install-language-grammer`. Seeing how you had already done that yourself earlier, this however is not the root cause of your issues (but something I have now corrected none-the-less)!

I was about to suggest `treesit-explore-mode`, but I see you discovered that for yourself.

It seems like there are elements inside your model declaration which is not supported, which makes the underlying grammar bug out completely, all the way to the top node. This is ofcouse not a very good user-experience 😒 

Looking into your sample DSL file I see there are a few problems:

* the `model` section contains an error: quoting error around `Some user"`.
* `softwareSystem` is in grammar expected to be all lower-case. This might be a grammar error which needs correcting.
* Entity interaction (`->`) expects only 1 textual description, not 2 as in your case. Is this officially supported grammar?
* the `views` contains (currently) unsupported element `systemContext`. support for this has not yet been added to the grammar.

This is very much a work in progress, and I'd like for the grammar to handle failures more gracefully and locally, to avoid the whole buffer being marked as invalid (which obviously is not very helpful).

Any help appreciated 😄

**Comment by josteink** [comment]
Thanks for the detailed write-up. I'm not using doom-emacs myself (just regular emacs from git source - roughly equivalent to Emacs 30).

Based on your comments, I'll just do my best to guide you, but I can't make any promises 😄 

> I've followed your instructions to get these:
>
> Configure tree-sitter

tree-sitter isn't anything you need to "configure". You need to have an Emacs build with tree-sitter support enabled.

Try evaluating `(treesit-available-p)` in the scratch-buffer. It should evaluate to `t`. If not, nothing else downstream from here is going to work.

> Install the tree-sitter-structurizr grammar

In theory you can install the package first, and the grammar afterwards, because then the package will add the grammar-source to the relevant tree-sitter lists so it appears as a choice when you do `M-x treesit-install-language-grammar`.

> Install the package via a (Doom Emacs) repo in .doom.d/packages.el:
> ;; Structurizr
> (package! structurizr-ts-mode
>   :recipe (:host nil :repo "https://github.com/josteink/structurizr-ts-mode"))

No experience with doom-emacs, so don't know how/if this works.

Have you tried the regular use-package instructions provided in the readme? Based on latest sources, they work fine for me.

**Comment by pohutukawa** [comment]
> josteink left a comment (josteink/structurizr-ts-mode#1)
> I see here that you have Emacs 29.4 at the core. This is what matters.

 
Yes, that's on my system by default using the MacOS Homebrew emacs-plus
install I have.
 

> It could be that treesit-language-source-alist which is used to
> pre-populate grammar repos was not available in this version. Apropros
> suggests it was added in 30.1.
> I've added a patch to only add to this list if present. If you try again
> now, it may work better?

 
Unfortunately that didn't make any difference. Still getting the same
error.
 
I'm currently trying to install `emacs-plus@30` to see if the Emacs 30.2
version will behave better.
 
I shall report back.

**Comment by josteink** [comment]
This may not be unexpected, actually.

It seems since I developed `structurizr-ts-mode` another major-mode has been added to Emacs which "steals" the `*.dsl` extension by default.

For debugging purposes, try open a `.dsl`-file and then do `M-x structurizr-ts-mode`.

If we're lucky, that's all that remains to be fixed.

**Comment by flying-spaghetti-monster** [comment]
Yes, I had noticed. It opens the workspace in `dsssl-mode`. I had switched to Structurizr mode with `M-x structurizr-ts-mode`.

Unfortunately that's where I had seen neither of the 'advertised' features to be in effect for me (highlighting and indentation support). :-/

**Comment by pohutukawa** [comment]
Sorry, for some strange reason the above last comment was posted under my work account.

**Comment by josteink** [comment]
Have you tried `M-x treesit-explore` once activated? What does it show?

**Comment by josteink** [comment]
The good news is that the major-mode is loaded then!

Now the grammar is incomplete and without localized error handling, which can make errors or unsupported elements blow up more than one would expect. 

Would it be possible for you to share the DSL-file so that I can better see what grammar elements bugs it out?

It might be easy to fix!

**Comment by pohutukawa** [comment]
@josteink, I have used another `workspace.dsl` file (renamed to `workspace.txt` for compatibility with HitGrub supported file types here) and renamed some work-related things in it to make it suitable for sharing.

[workspace.txt](https://github.com/user-attachments/files/23534777/workspace.txt)

**Comment by josteink** [comment]
Seeing as most of the comments in this thread is no longer about "basic install" or "documentation", but about missing features, I'm opting to close this issue.

I will be creating separate issues for all unsupported syntax elements mentioned in this thread, and forward link to them from this thread for easy access.

Thanks to all of you for helping make this major-mode less alpha than it used to be 😃
